package com.example.springTest.model;

import java.util.Date;

public class AccessLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.access_log.log_id
     *
     * @mbg.generated Sat May 06 20:26:14 GMT+09:00 2023
     */
    private Long logId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.access_log.access_time
     *
     * @mbg.generated Sat May 06 20:26:14 GMT+09:00 2023
     */
    private Date accessTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.access_log.request_path
     *
     * @mbg.generated Sat May 06 20:26:14 GMT+09:00 2023
     */
    private String requestPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.access_log.param
     *
     * @mbg.generated Sat May 06 20:26:14 GMT+09:00 2023
     */
    private String param;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.access_log.ip_address
     *
     * @mbg.generated Sat May 06 20:26:14 GMT+09:00 2023
     */
    private String ipAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.access_log.user_agent
     *
     * @mbg.generated Sat May 06 20:26:14 GMT+09:00 2023
     */
    private String userAgent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.access_log.host_name
     *
     * @mbg.generated Sat May 06 20:26:14 GMT+09:00 2023
     */
    private String hostName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.access_log.referrer
     *
     * @mbg.generated Sat May 06 20:26:14 GMT+09:00 2023
     */
    private String referrer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.access_log.warning_flg
     *
     * @mbg.generated Sat May 06 20:26:14 GMT+09:00 2023
     */
    private Boolean warningFlg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.access_log.log_id
     *
     * @return the value of public.access_log.log_id
     *
     * @mbg.generated Sat May 06 20:26:14 GMT+09:00 2023
     */
    public Long getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.access_log.log_id
     *
     * @param logId the value for public.access_log.log_id
     *
     * @mbg.generated Sat May 06 20:26:14 GMT+09:00 2023
     */
    public void setLogId(Long logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.access_log.access_time
     *
     * @return the value of public.access_log.access_time
     *
     * @mbg.generated Sat May 06 20:26:14 GMT+09:00 2023
     */
    public Date getAccessTime() {
        return accessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.access_log.access_time
     *
     * @param accessTime the value for public.access_log.access_time
     *
     * @mbg.generated Sat May 06 20:26:14 GMT+09:00 2023
     */
    public void setAccessTime(Date accessTime) {
        this.accessTime = accessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.access_log.request_path
     *
     * @return the value of public.access_log.request_path
     *
     * @mbg.generated Sat May 06 20:26:14 GMT+09:00 2023
     */
    public String getRequestPath() {
        return requestPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.access_log.request_path
     *
     * @param requestPath the value for public.access_log.request_path
     *
     * @mbg.generated Sat May 06 20:26:14 GMT+09:00 2023
     */
    public void setRequestPath(String requestPath) {
        this.requestPath = requestPath == null ? null : requestPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.access_log.param
     *
     * @return the value of public.access_log.param
     *
     * @mbg.generated Sat May 06 20:26:14 GMT+09:00 2023
     */
    public String getParam() {
        return param;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.access_log.param
     *
     * @param param the value for public.access_log.param
     *
     * @mbg.generated Sat May 06 20:26:14 GMT+09:00 2023
     */
    public void setParam(String param) {
        this.param = param == null ? null : param.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.access_log.ip_address
     *
     * @return the value of public.access_log.ip_address
     *
     * @mbg.generated Sat May 06 20:26:14 GMT+09:00 2023
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.access_log.ip_address
     *
     * @param ipAddress the value for public.access_log.ip_address
     *
     * @mbg.generated Sat May 06 20:26:14 GMT+09:00 2023
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress == null ? null : ipAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.access_log.user_agent
     *
     * @return the value of public.access_log.user_agent
     *
     * @mbg.generated Sat May 06 20:26:14 GMT+09:00 2023
     */
    public String getUserAgent() {
        return userAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.access_log.user_agent
     *
     * @param userAgent the value for public.access_log.user_agent
     *
     * @mbg.generated Sat May 06 20:26:14 GMT+09:00 2023
     */
    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent == null ? null : userAgent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.access_log.host_name
     *
     * @return the value of public.access_log.host_name
     *
     * @mbg.generated Sat May 06 20:26:14 GMT+09:00 2023
     */
    public String getHostName() {
        return hostName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.access_log.host_name
     *
     * @param hostName the value for public.access_log.host_name
     *
     * @mbg.generated Sat May 06 20:26:14 GMT+09:00 2023
     */
    public void setHostName(String hostName) {
        this.hostName = hostName == null ? null : hostName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.access_log.referrer
     *
     * @return the value of public.access_log.referrer
     *
     * @mbg.generated Sat May 06 20:26:14 GMT+09:00 2023
     */
    public String getReferrer() {
        return referrer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.access_log.referrer
     *
     * @param referrer the value for public.access_log.referrer
     *
     * @mbg.generated Sat May 06 20:26:14 GMT+09:00 2023
     */
    public void setReferrer(String referrer) {
        this.referrer = referrer == null ? null : referrer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.access_log.warning_flg
     *
     * @return the value of public.access_log.warning_flg
     *
     * @mbg.generated Sat May 06 20:26:14 GMT+09:00 2023
     */
    public Boolean getWarningFlg() {
        return warningFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.access_log.warning_flg
     *
     * @param warningFlg the value for public.access_log.warning_flg
     *
     * @mbg.generated Sat May 06 20:26:14 GMT+09:00 2023
     */
    public void setWarningFlg(Boolean warningFlg) {
        this.warningFlg = warningFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.access_log
     *
     * @mbg.generated Sat May 06 20:26:14 GMT+09:00 2023
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AccessLog other = (AccessLog) that;
        return (this.getLogId() == null ? other.getLogId() == null : this.getLogId().equals(other.getLogId()))
            && (this.getAccessTime() == null ? other.getAccessTime() == null : this.getAccessTime().equals(other.getAccessTime()))
            && (this.getRequestPath() == null ? other.getRequestPath() == null : this.getRequestPath().equals(other.getRequestPath()))
            && (this.getParam() == null ? other.getParam() == null : this.getParam().equals(other.getParam()))
            && (this.getIpAddress() == null ? other.getIpAddress() == null : this.getIpAddress().equals(other.getIpAddress()))
            && (this.getUserAgent() == null ? other.getUserAgent() == null : this.getUserAgent().equals(other.getUserAgent()))
            && (this.getHostName() == null ? other.getHostName() == null : this.getHostName().equals(other.getHostName()))
            && (this.getReferrer() == null ? other.getReferrer() == null : this.getReferrer().equals(other.getReferrer()))
            && (this.getWarningFlg() == null ? other.getWarningFlg() == null : this.getWarningFlg().equals(other.getWarningFlg()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.access_log
     *
     * @mbg.generated Sat May 06 20:26:14 GMT+09:00 2023
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getLogId() == null) ? 0 : getLogId().hashCode());
        result = prime * result + ((getAccessTime() == null) ? 0 : getAccessTime().hashCode());
        result = prime * result + ((getRequestPath() == null) ? 0 : getRequestPath().hashCode());
        result = prime * result + ((getParam() == null) ? 0 : getParam().hashCode());
        result = prime * result + ((getIpAddress() == null) ? 0 : getIpAddress().hashCode());
        result = prime * result + ((getUserAgent() == null) ? 0 : getUserAgent().hashCode());
        result = prime * result + ((getHostName() == null) ? 0 : getHostName().hashCode());
        result = prime * result + ((getReferrer() == null) ? 0 : getReferrer().hashCode());
        result = prime * result + ((getWarningFlg() == null) ? 0 : getWarningFlg().hashCode());
        return result;
    }
}