package com.example.springTest.model;

import java.time.LocalDateTime;

public class Comments {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.comments.comment_id
     *
     * @mbg.generated Wed Jul 26 00:01:51 GMT+09:00 2023
     */
    private Long commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.comments.article_id
     *
     * @mbg.generated Wed Jul 26 00:01:51 GMT+09:00 2023
     */
    private Long articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.comments.user_name
     *
     * @mbg.generated Wed Jul 26 00:01:51 GMT+09:00 2023
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.comments.post_date_time
     *
     * @mbg.generated Wed Jul 26 00:01:51 GMT+09:00 2023
     */
    private LocalDateTime postDateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.comments.comment_content
     *
     * @mbg.generated Wed Jul 26 00:01:51 GMT+09:00 2023
     */
    private String commentContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.comments.num_of_chars
     *
     * @mbg.generated Wed Jul 26 00:01:51 GMT+09:00 2023
     */
    private Long numOfChars;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.comments.registration_time
     *
     * @mbg.generated Wed Jul 26 00:01:51 GMT+09:00 2023
     */
    private LocalDateTime registrationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.comments.update_time
     *
     * @mbg.generated Wed Jul 26 00:01:51 GMT+09:00 2023
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.comments.delete_flg
     *
     * @mbg.generated Wed Jul 26 00:01:51 GMT+09:00 2023
     */
    private Boolean deleteFlg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.comments.comment_id
     *
     * @return the value of public.comments.comment_id
     *
     * @mbg.generated Wed Jul 26 00:01:51 GMT+09:00 2023
     */
    public Long getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.comments.comment_id
     *
     * @param commentId the value for public.comments.comment_id
     *
     * @mbg.generated Wed Jul 26 00:01:51 GMT+09:00 2023
     */
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.comments.article_id
     *
     * @return the value of public.comments.article_id
     *
     * @mbg.generated Wed Jul 26 00:01:51 GMT+09:00 2023
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.comments.article_id
     *
     * @param articleId the value for public.comments.article_id
     *
     * @mbg.generated Wed Jul 26 00:01:51 GMT+09:00 2023
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.comments.user_name
     *
     * @return the value of public.comments.user_name
     *
     * @mbg.generated Wed Jul 26 00:01:51 GMT+09:00 2023
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.comments.user_name
     *
     * @param userName the value for public.comments.user_name
     *
     * @mbg.generated Wed Jul 26 00:01:51 GMT+09:00 2023
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.comments.post_date_time
     *
     * @return the value of public.comments.post_date_time
     *
     * @mbg.generated Wed Jul 26 00:01:51 GMT+09:00 2023
     */
    public LocalDateTime getPostDateTime() {
        return postDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.comments.post_date_time
     *
     * @param postDateTime the value for public.comments.post_date_time
     *
     * @mbg.generated Wed Jul 26 00:01:51 GMT+09:00 2023
     */
    public void setPostDateTime(LocalDateTime postDateTime) {
        this.postDateTime = postDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.comments.comment_content
     *
     * @return the value of public.comments.comment_content
     *
     * @mbg.generated Wed Jul 26 00:01:51 GMT+09:00 2023
     */
    public String getCommentContent() {
        return commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.comments.comment_content
     *
     * @param commentContent the value for public.comments.comment_content
     *
     * @mbg.generated Wed Jul 26 00:01:51 GMT+09:00 2023
     */
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent == null ? null : commentContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.comments.num_of_chars
     *
     * @return the value of public.comments.num_of_chars
     *
     * @mbg.generated Wed Jul 26 00:01:51 GMT+09:00 2023
     */
    public Long getNumOfChars() {
        return numOfChars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.comments.num_of_chars
     *
     * @param numOfChars the value for public.comments.num_of_chars
     *
     * @mbg.generated Wed Jul 26 00:01:51 GMT+09:00 2023
     */
    public void setNumOfChars(Long numOfChars) {
        this.numOfChars = numOfChars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.comments.registration_time
     *
     * @return the value of public.comments.registration_time
     *
     * @mbg.generated Wed Jul 26 00:01:51 GMT+09:00 2023
     */
    public LocalDateTime getRegistrationTime() {
        return registrationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.comments.registration_time
     *
     * @param registrationTime the value for public.comments.registration_time
     *
     * @mbg.generated Wed Jul 26 00:01:51 GMT+09:00 2023
     */
    public void setRegistrationTime(LocalDateTime registrationTime) {
        this.registrationTime = registrationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.comments.update_time
     *
     * @return the value of public.comments.update_time
     *
     * @mbg.generated Wed Jul 26 00:01:51 GMT+09:00 2023
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.comments.update_time
     *
     * @param updateTime the value for public.comments.update_time
     *
     * @mbg.generated Wed Jul 26 00:01:51 GMT+09:00 2023
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.comments.delete_flg
     *
     * @return the value of public.comments.delete_flg
     *
     * @mbg.generated Wed Jul 26 00:01:51 GMT+09:00 2023
     */
    public Boolean getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.comments.delete_flg
     *
     * @param deleteFlg the value for public.comments.delete_flg
     *
     * @mbg.generated Wed Jul 26 00:01:51 GMT+09:00 2023
     */
    public void setDeleteFlg(Boolean deleteFlg) {
        this.deleteFlg = deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.comments
     *
     * @mbg.generated Wed Jul 26 00:01:51 GMT+09:00 2023
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Comments other = (Comments) that;
        return (this.getCommentId() == null ? other.getCommentId() == null : this.getCommentId().equals(other.getCommentId()))
            && (this.getArticleId() == null ? other.getArticleId() == null : this.getArticleId().equals(other.getArticleId()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getPostDateTime() == null ? other.getPostDateTime() == null : this.getPostDateTime().equals(other.getPostDateTime()))
            && (this.getCommentContent() == null ? other.getCommentContent() == null : this.getCommentContent().equals(other.getCommentContent()))
            && (this.getNumOfChars() == null ? other.getNumOfChars() == null : this.getNumOfChars().equals(other.getNumOfChars()))
            && (this.getRegistrationTime() == null ? other.getRegistrationTime() == null : this.getRegistrationTime().equals(other.getRegistrationTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDeleteFlg() == null ? other.getDeleteFlg() == null : this.getDeleteFlg().equals(other.getDeleteFlg()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.comments
     *
     * @mbg.generated Wed Jul 26 00:01:51 GMT+09:00 2023
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCommentId() == null) ? 0 : getCommentId().hashCode());
        result = prime * result + ((getArticleId() == null) ? 0 : getArticleId().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getPostDateTime() == null) ? 0 : getPostDateTime().hashCode());
        result = prime * result + ((getCommentContent() == null) ? 0 : getCommentContent().hashCode());
        result = prime * result + ((getNumOfChars() == null) ? 0 : getNumOfChars().hashCode());
        result = prime * result + ((getRegistrationTime() == null) ? 0 : getRegistrationTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDeleteFlg() == null) ? 0 : getDeleteFlg().hashCode());
        return result;
    }
}